* 最优化
** 凸集
凸集(convex set)是在凸组合下闭合的仿射空间的子集。更具体地说，在欧氏空间中，凸集是对于集合内的每一对点，连接该对点的直线段上的每个点也在该集合内。例如，立方体是凸集，但是任何中空的或具有凹痕的例如月牙形都不是凸集。
** ~凸优化问题~
研究定义于凸集中的凸函数最小化的问题。
*** 性质
凸优化中局部最优值必定是全局最优解。

** ~拉格朗日乘子法~
拉格朗日乘子法（Lagrange Multiplier）和 KKT (Karush Kuhn Tucker)条件是两种最常见求解最优化问题方法。 在有等式约束时使用拉格朗日乘子法，在有不等式约束时使用KKT条件。
*** 等式约束条件
设定目标函数为 $f(x)$, 约束条件为 $h_k(x)$, 形如：
\begin{equation}
\label{eq:1}
\begin{align}
&\min f \left( i \right)\\
&s.t. \quad h_k \left( x \right) = 0 \quad k=1,2,...,l
\end{align}
\end{equation}
首先定义拉格朗日函数 $F(x)$:
                     \begin{equation}
\label{eq:3}
F \left( x, \lambda \right) = f \left( x \right) + \sum\limits_{k=1}^l \lambda_k h_k \left( x \right)
\end{equation}
然后求解变量的偏导方程:
\begin{equation}
\label{eq:4}
\frac{\partial F}{\partial x_i} = 0 \quad ... \quad \frac{\partial F}{\partial \lambda_k} = 0
\end{equation}
如果有 $l$ 个约束条件使用 $l+1$ 个方程。
[[https://www.jianshu.com/p/3c51007cd405][几何解释]]

*** 不等式约束条件
设定目标函数为 $f(x)$, 等式约束条件为 $h_k(x)$, 不等式约束条件 $g_k \left( x \right)<=0$ 形如：
\begin{equation}
\label{eq:1}
\begin{align}
&\min f \left( x \right)\\
&s.t. \quad h_k \left( x \right) = 0 \quad j=1,2,...,p\\
&\qquad g_k \left( X \right) \leqslant 0 \quad k=1,2,...,q
\end{align}
\end{equation}

KKT 条件是说最优值必须满足一下条件:
\begin{equation}
\label{eq:8}
L \left( x, \lambda, \mu \right) = f \left( x \right) + \sum\limits_{j=1}^p \lambda_j h_j \left( x \right) + \sum\limits_{k=1}^q \mu_k g_k \left( x \right)
\end{equation}
(1) $\frac{\partial L}{\partial x}=0$, $\frac{\partial L}{ \partial \lambda}=0$, $\frac{\partial L}{\partial \mu} =0$
(2) $\mu_k g_k \left( x \right) =0$
(3) $h_j \left( x \right) = 0$
(4) $\mu \geq 0$ 
[[https://blog.csdn.net/mingWar/article/details/62889775][KKT条件推导及证明]]

\begin{equation}
\label{eq:9}
\min_{w} \max_{\mu} L
\end{equation}

*** 对偶关系与KKT条件
原问题与对偶问题为强对偶关系 等于与 满足KKT条件

** ~二次规划问题 (Quadratic Programming Problem)~
二次规划问题可以利用现有的一些套件进行求解。
二次规划问题的一般形式表示:
\begin{equation}
\label{eq:5}
\begin{align}
&\min_x q \left( x \right) = \frac{1}{2} x^T G x + x^Tc \\
&s.t. \quad a_i^T x \geq b_i, \quad i \in \tau
\end{align}
\end{equation}
其中 G 为 Hessian 矩阵， $\tau$ 是有效指标集, $c, x, a_i \in R$. 
*** Hessian Matrix
黑塞矩阵（Hessian Matrix）, 又译作海森矩阵、海瑟矩阵、海塞矩阵等，是一个多元函数的二阶偏导数构成的方阵

** ~对偶问题~
弱对偶关系 $\geqslant$, 强对偶关系 $=$

当问题为非凸优化问题时，$\min \max$ 与 $\max \min$ 为弱对偶问题。
\begin{equation}
\label{eq:10}
\min \max \mathcal{L} \geqslant \max \min \mathcal{L}
\end{equation}
当问题为凸优化问题并且满足 [[*Slater %E6%9D%A1%E4%BB%B6][Slater条件]] 时, $\min \max$ 与 $\max \min$ 变为了强对偶关系 (此为充分条件非必要条件)
\begin{equation}
\label{eq:10}
\min \max \mathcal{L} = \max \min \mathcal{L}
\end{equation}
*凸二次规划问题* 满足Slater条件, SVM 本质为二次优化问题， 因此推导的过程中使用了强对偶关系的性质。
[[https://baike.baidu.com/item/对偶理论/9582786?fr=aladdin][百度百科参考资料]]
*** 约束优化问题等价性证明
**** 原问题 (Primal Problem)

\begin{equation}
\label{eq:12}
\begin{align}
\label{eq:13}
&\min_{x\in \mathbb{R}^P} f \left( x \right) \\
&s.t. \quad m_i \left( x \right) \leq 0, i=1,...,M\\
&\qquad n_j \left( x \right) = 0, j =1,...,N
\end{align}
\end{equation}
**** 无约束条件的原问题
引入拉格朗日函数将问题转化为无约束的原问题
\begin{equation}
\label{eq:14}
\begin{align}
\label{eq:15}
&\mathcal{L} \left( x,\lambda, \mu \right) = f \left( x \right) + \sum\limits_{i=1}^M \lambda_i m_i + \sum\limits_{j=1}^N \mu_{j} n_j\\
& \min_x \max_{\lambda,\mu} \mathcal{L} \left( x, \lambda, \mu \right) \\
& s.t. \quad \lambda_i  \geq 0
\end{align}
\end{equation}
**** 等价性证明
当 $x$ 违反了约束条件 $m_i \left( x \right) \geq 0$, $\max_{\lambda} \mathcal{L} = +\infty$
当 $x$ 满足了约束条件 $m_i \left( x \right) \leq 0$, $\max_{\lambda} \mathcal{L} \neq +\infty$  
因此 $\min_x \max_{\lambda} \mathcal{L}$ 仅仅能取到满足约束条件的 $x$ 的函数值.
*** 弱对偶性
对偶问题(d) $\leq$ 原问题(p)
**** 原问题与对偶问题
原问题:
\begin{equation}
\label{eq:20}
\min_x \max_{\lambda,\mu} \mathcal{L} \left( x, \lambda,\mu \right)
\end{equation}
对偶问题:
\begin{equation}
\label{eq:21}
\max_{\lambda,\mu} \min_x \mathcal{L} \left( x,\lambda,\mu \right) 
\end{equation}
**** 弱对偶性证明
对于任意 $x,\lambda,\mu$, 满足:
\begin{equation}
\label{eq:16}
\min_x \mathcal{L} \left( x,\lambda,\mu \right) \leq \mathcal{L} \left( x,\lambda,\mu \right) \leq \max_{\lambda,\mu} \left( x,\lambda,\mu \right)
\end{equation}
我们设 $A(\lambda,\mu) = \min_x \mathcal{L} \left( x,\lambda,\mu \right)$, $B(x) = \max_{\lambda,\mu} \left( x,\lambda,\mu \right)$, 可以得到
\begin{equation}
\label{eq:17}
A \left( \lambda,\mu \right) \leq B \left( x \right)
\end{equation}
也就是说 
\begin{equation}
\label{eq:18}
\begin{align}
\label{eq:19}
&\max_{\lambda,\mu} A \left( \lambda,\mu \right) \leq \min_x B \left( x \right)\\
&\max_{\lambda,\mu} \min_x \mathcal{L} \left( x,\lambda,\mu \right) \leq \min_x \max_{\lambda,\mu} \mathcal{L} \left( x, \lambda,\mu \right)
\end{align}
\end{equation}
*** 对偶性的几何解释
$P^{* } = \min_x f \left( x \right)$ 原问题最优解
$d^{* } = \max_{\lambda} \min_x \mathcal{L} \left( x, \lambda \right)$  对偶问题最优解
\begin{equation}
\label{eq:24}
\begin{align}
\label{eq:25}
G &= \left\{ \left( m_1 \left( x \right), f \left( x \right) \right) | x\in D \right\}\\
&= \left\{ \left( u,t \right) | x \in D \right\}
\end{align}
\end{equation}

通过集合表示 $P^{*}$
\begin{equation}
\label{eq:26}
P^{*} = inf \left\{ t | \left( u,t \right) \in G, u \leq 0 \right\}
\end{equation}
\begin{equation}
\label{eq:27}
\begin{align}
\label{eq:28}
d^{*} &= \max_{\lambda} \min_x \mathcal{L} \left( x, \lambda \right) \\
&= \max_{\lambda} \min_x \left( t + \lambda u \right)\\
&= \max_{\lambda} g \left( \lambda \right)\\
\end{align}
\end{equation}

通过集合表示 $g \left( \lambda \right)$
\begin{equation}
\label{eq:30}
g \left( \lambda \right) = inf \left\{ t + \lambda u | \left( u,t \right) \in G \right\}
\end{equation}

$t + \lambda u = C$ 可以看做一条直线 ($\lambda$ 为直线的斜率)， 结果是找经过 $G$ 并且 $t$ 轴的交点值最小的直线。

*** Slater 条件
如果原问题是一个凸优化问题，存在 $\rilde{x} \in relint D$ 使得: $f_i \left(\tilde{x}\right) < 0$, 对任意 $i=1,2,...,m$, 则原问题和对偶问题是强对偶的。
**** 原问题表示形式
原问题表示形式:
\begin{equation}
\label{eq:31}
\begin{align}
\label{eq:32}
&\min f_0 \left( x \right)\\
&s.t. \quad f_i \left( x \right) \leq 0, i=1,...,m\\
&\qquad h_i \left( x \right) \leq 0, i=1,...,p
\end{align}
\end{equation}
*** 仿射函数
** 待整理问题
1. 判断是否是凸优化问题
   + 判断是否是凸函数
   + 判断是否是凸集
3. 判断是否满足Slater 条件
